### ISSUE TITLE
Better warning when you don't have java installed

### ISSUE THREAD

**Issue by jwheare** [sstephenson/ruby-yui-compressor#1]
At the moment you just get the "compression failed" RuntimeError in the compress method.

If you poke that exception a bit more it says there was a Broken Pipe error in the Open3.popen3(*command) call which you can then trace to the @command in initialize to see that the java call is failing.

This took me a little while as I'm not that familiar with ruby, and didn't really understand what that popen3 command was doing.

Maybe at a test for java that raises a more descriptive exception earlier on?

**Comment by tfln** [comment]
seconded.  Thanks for the solution :)

**Comment by anuaimi** [comment]
all that is probably required is to add a puts with the exception message. that is how I found out why the compression was failing (in regards to another issue).

```
      rescue Exception => e
        puts e.message
        raise RuntimeError, "compression failed"
```

**Comment by stevecrozz** [comment]
This issue should be resolved now. I added my comments on https://github.com/sstephenson/ruby-yui-compressor/pull/20
