### ISSUE TITLE
Jammit 0.9.5 hangs on Mac OS X and Linux

### ISSUE THREAD

**Issue by jsl** [sstephenson/ruby-yui-compressor#12]
The library at #e24acb3 hangs in our environment when used with Jammit.  In particular, it looks like the stderr.read invocation that was added in this commit breaks things for us.  Downgrading to 0.9.4 fixes the issue.

**Comment by sstephenson** [comment]
Do the tests pass for you, or do they hang?

```
RUBYOPT="-Ilib -Itest -rubygems" rake test
```

What version of Ruby are you using?

If the tests pass for you, let's try to find a failing/hanging test case.

**Comment by jsl** [comment]
Hi Sam,

I wanted to let you know that this issue has been raised on the jammit project as well: https://github.com/documentcloud/jammit/issues#issue/155

It appears to essentially break jammit, since on any significant amount of input yui-compressor hangs.

I've written a test case that reproduces this issue here:

https://github.com/jsl/ruby-yui-compressor/commit/4e7fa47648a4a143a46dcb44e818875cd0e7e998

I believe that with files slightly larger than the test JS files, the new code causes the child process to go to sleep.  I'm not sure of the mechanics of this, but it is alluded to in this thread: http://www.ruby-forum.com/topic/166832.  It seems like a more sophisticated approach to reading from stderr and stdout is needed to ensure that this doesn't happen.

I feel like the best thing to do would be to revert the recent change which tries to read stderr, and bump the version to 0.9.6 so that the compressor starts working again.  I've done this in my fork, which I pushed a moment ago.  

In my fork I also updated YUI::Compressor::VERSION, which it appears we missed in the 0.9.5 push, this caused some strange gem loading behavior for me while I was diagnosing this issue.  

I've updated all the places where the version appears in my fork, and my reversion of the code makes my failing test pass, so it should be clear to push a new gem, after you do some testing to verify my fix.

Thanks for your work on yui-compressor!

Justin

**Comment by zimdo** [comment]
I can confirm this with ruby 1.9.2 and rails-3 and recent jammit. It was working fine 0.9.4.

**Comment by jsl** [comment]
I've reproduced the hanging behavior on ree and 1.8.7 on Mac OS X and Linux.

**Comment by sstephenson** [comment]
Alright, thanks for the failing test case. I've pushed version 0.9.6 which uses the POpen4 gem to invoke YUI Compressor. Instead of reading from stderr, it now raises an exception if there's a non-zero exit status.

Could you give this version a try and let me know if everything works?

**Comment by jsl** [comment]
0.9.6 works for us.  Popen4 seems like a good solution, since popen3 doesn't seem to provide a way to get the return value, at least on Ruby 1.8.7.  Thanks!
