### ISSUE TITLE
POpen4

### ISSUE THREAD

**Issue by nesizer** [sstephenson/ruby-yui-compressor#15]
the use of POpen4 makes it  impossible to use on windows with ruby 1.9.2 even with the win32-open3-19 gem
and on 1.8.7 it just says "no such file or directory" when try to execute this code

```
require "yui/compressor"
compressor = YUI::JavaScriptCompressor.new
compressor.compress('(function () { var foo = {}; foo["bar"] = "baz"; })()')
```

**Comment by nesizer** [comment]
forgot to say i'm on windows 7 x64

**Comment by nesizer** [comment]
it looks like it a windows 64bit problem just try it on windows 32bit machine and ruby 1.8.7 and it works

**Comment by sstephenson** [comment]
I'd suggest taking this up with the POpen4 project, then. (That was the whole idea behind using it.)

Alternatively, upgrade to a better OS ;)

**Comment by kibblr** [comment]
a) it's happening under linux too and b) popen4 seems to be abandoned and hasn't had an update in 5 years.

/usr/lib/ruby/gems/1.8/gems/POpen4-0.1.4/lib/popen4.rb:81: [BUG] Segmentation fault

ruby 1.8.7 (2010-06-23 patchlevel 299) [i686-linux]

& all the way up to 1.8.7p352
1. https://github.com/documentcloud/jammit/issues/166
2. http://groups.google.com/group/diaspora-dev/browse_thread/thread/0a15dd84b0626513
3. https://gist.github.com/1016667

**Comment by pietia** [comment]
Same here , OSX

**Comment by stevecrozz** [comment]
Agreed. POpen4 doesn't really deliver on its promise to:
"provides the Rubyist a single API across platforms for executing a command in a child process with handles on stdout, stderr, stdin streams as well as access to the process ID and exit status"

You'll be happy to know that I've dropped this gem's dependence on POpen4 by merging a nice pull request from @kares: https://github.com/sstephenson/ruby-yui-compressor/pull/14
