### ISSUE TITLE
0.9.6 not ruby 1.8.6 compatible

### ISSUE THREAD

**Issue by wezm** [sstephenson/ruby-yui-compressor#16]
When running yui-compressor v0.9.6 under ruby 1.8.6 the following error occurs. I believe this is due to differences between Shellwords in ruby 1.8.6 and 1.8.7.

```
shared/bundle/ruby/1.8/gems/yui-compressor-0.9.6/lib/yui/compressor.rb:29:in `command': undefined method `escape' for Shellwords:Module (NoMethodError)
```

**Comment by stevecrozz** [comment]
I've just started maintaining this gem, but adding support for ruby 1.8.6 is not at the top of my list. Although I'd accept a pull request if you want to put one in.
