### ISSUE TITLE
require in irb on Windows XP fails

### ISSUE THREAD

**Issue by belgoros** [sstephenson/ruby-yui-compressor#24]
During the installation I had the following warning:

C:>gem install yui-compressor
Fetching: Platform-0.4.0.gem (100%)
WARNING: Platform-0.4.0 has an invalid nil value for @cert_chain
Fetching: open4-1.3.0.gem (100%)
Fetching: POpen4-0.1.4.gem (100%)
Fetching: yui-compressor-0.9.6.gem (100%)
Successfully installed Platform-0.4.0
Successfully installed open4-1.3.0
Successfully installed POpen4-0.1.4
Successfully installed yui-compressor-0.9.6
4 gems installed
Installing ri documentation for Platform-0.4.0...
Installing ri documentation for open4-1.3.0...
Installing ri documentation for POpen4-0.1.4...
Installing ri documentation for yui-compressor-0.9.6...
Installing RDoc documentation for Platform-0.4.0...
Installing RDoc documentation for open4-1.3.0...
Installing RDoc documentation for POpen4-0.1.4...
Installing RDoc documentation for yui-compressor-0.9.6...

Then when trying to require it in irb, I got the below error:
    C:>irb -rubygems
irb(main):001:0> require "yui/compressor"
LoadError: no such file to load -- win32/open3
        from C:/Ruby192/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from C:/Ruby192/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in`require'
        from C:/Ruby192/lib/ruby/gems/1.9.1/gems/POpen4-0.1.4/lib/popen4.rb:9:in `<top (required)>'
        from C:/Ruby192/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in`require'
        from C:/Ruby192/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from C:/Ruby192/lib/ruby/gems/1.9.1/gems/yui-compressor-0.9.6/lib/yui/compressor.rb:1:in`<top (required)>'
        from C:/Ruby192/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:57:in `require'
        from C:/Ruby192/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:57:in`rescue in require'
        from C:/Ruby192/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:35:in `require'
        from (irb):1
        from C:/Ruby192/bin/irb:12:in`<main>'

I 'm on Windows XP SP2
Ruby 1.9.2

On Ubuntu  10.04 I had the same warning during the installation but no problems when requiring it in the 'irb'.

**Comment by wesleyalcoforado** [comment]
Same thing here on Windows 7 32 bits / Ruby 1.9.3

**Comment by wesleyalcoforado** [comment]
Installing win32-open3-19 solves the problem

**Comment by stevecrozz** [comment]
We're now using tempfiles instead of POpen4, so this should no longer be an issue.
