### ISSUE TITLE
Is there an active maintainer for this code?  If not can we get one?

### ISSUE THREAD

**Issue by Altonymous** [sstephenson/ruby-yui-compressor#28]
Seems like there are multiple pull requests for things on this gem and no one actively maintaining it.  Can we add some people to the repo or transfer it to someone else to maintain?  

I'll volunteer.

**Comment by stevecrozz** [comment]
Yep. I'm picking up maintenance of this gem, and you're certainly welcome to contribute if you have suggestions.
