### ISSUE TITLE
truncates % in CSS

### ISSUE THREAD

**Issue by ghost** [sstephenson/ruby-yui-compressor#34]
1.9.3p392 :027 > compressor.compress(<<-END_CSS)
1.9.3p392 :028"> .test{width: 20%; }
1.9.3p392 :029"> .test2{width: 20.0%}
1.9.3p392 :030"> END_CSS
 => ".test{width:20%}.test2{width:20.0}"

**Comment by stevecrozz** [comment]
It looks like this is a bug in yuicompressor:

``` bash
echo '.test{width: 20.0%;}' | java -jar lib/yuicompressor-2.4.8.jar --type css
.test{width:20.0}
```

I've opened a ticket for you upstream: https://github.com/yui/yuicompressor/issues/132.
