### ISSUE TITLE
Fail early if java is not installed

### ISSUE THREAD

**Issue by betesh** [sstephenson/ruby-yui-compressor#38]
In my case, I'm running `rake assets:precompile` on a Rails 3.2 project.  It fails with this message:

```
** Execute assets:precompile:all
rake aborted!
undefined method `exitstatus' for nil:NilClass
~/.rvm/gems/ruby-1.9.3-p392/gems/yui-compressor-0.9.6/lib/yui/compressor.rb:84:in `block in compress'
[and the rest of the stack trace]
```

Not too useful.  More useful would be:

```
YUICompressor requires java to be installed.  Please run `(sudo) apt-get|yum install default-jre`
```

Don't forget that you can decide whether to use apt-get or yum in the exit message by checking what system you are on.  At the very least, use `which apt-get`.  Also, I'm not 100% sure default-jre is always the right choice, so please use whatever package name is appropriate.

**Comment by stevecrozz** [comment]
Hi @betesh,

Are you able to use a newer version of this gem? The latest version is v0.12.0 and the message is now moderately more helpful. You should see something like this:

```
YUI::Compressor::RuntimeError: Command 'java -jar ./lib/yui/../yuicompressor-2.4.8.jar --type js --nomunge --charset utf-8 --line-break 0 /tmp/yui_compress20140220-29673-4kbk1e-0' returned non-zero exit status
    ./lib/yui/compressor.rb:106:in `compress'
    ./lib/yui/compressor.rb:141:in `streamify'
    ./lib/yui/compressor.rb:86:in `compress'
    test/compressor_test.rb:117:in `test_line_break_option_should_insert_line_breaks_in_js'
```

**Comment by betesh** [comment]
Thanks for the suggestion.  I'll gladly upgrade, but I still think you can do better than 'moderately more helpful'.  Remember that it's not just about the message--it's also about the speed with which the message appears--it can be at load time instead of at run time.

**Comment by stevecrozz** [comment]
It sounds nice, but it has to be balanced with other requirements. For instance, some people have to specify a custom path to java and that configuration is set when you instantiate a YUI::Compressor object. Also, I personally wouldn't any of the gems I use to fork off a subprocess before I even use them. But it sounds like maybe you would want exactly that.

I bet we could come up with something though. I'd say it should not fork off an extra subprocesses unless the user has opted in to this approach. It should maintain backwards compatiblity and continue to work on all the various platforms we support (ruby18,ruby19,ruby2x,rbx,jruby,windows,linux,mac). Add in some unit tests and that sounds like something I would merge! Now I just need a PR :)

**Comment by betesh** [comment]
I get the message--you want me to do the leg work.  I can give it a try, and if the first attempt doesn't have adequate unit tests, just let me know and I'll keep working at it.

But first, I'm clearly missing something--Why must checking whether java is installed be in a forked subprocess?  It seems to me that I could run `which #{path_to_java}` in initialize and, if it returns empty, exit immediately, or at least log an error and not allow you to call any methods the object.  The only risk is what if you have other forked processes running--so please fill me in one what would happen if I exited in such a case.  Could different YUI::Compressors in the same parent process use different `path_to_java`'s?

If you can clarify all of that for me, then I just need to find the Windows equivalent of `/usr/bin/which`.

**Comment by betesh** [comment]
Submitted PR #40 for this.  We can continue the conversation there.
