### ISSUE TITLE
Problems with CircleCi 

### ISSUE THREAD

**Issue by voleoo** [sstephenson/ruby-yui-compressor#43]
When i'm testing on CircleCi my app with yui-compressor i have warning

```
Warning: The build VMs have a memory limit of 4G. Your build hit this limit on one or more containers, and your build results are likely invalid.
```

How can i set limit of memory for yui-compressor

**Comment by xxthegonzxx** [comment]
@voleoo, did you ever solve this?

**Comment by voleoo** [comment]
Yes, you can limit memory via parameters, please look at
https://github.com/sstephenson/ruby-yui-compressor/blob/7604d65bf2c88bfd826b340f0507cf69d831648e/test/compressor_test.rb#L45

**Comment by xxthegonzxx** [comment]
Thank you @voleoo, this has solved my problem!
